trigger: 
  branches:
    include:
    - main
  paths:
    include:
    - app


variables:
  azureServiceConnectionId: '<your service connection>'
  webAppName: '<your Azure App Service>'
  projectRoot: $(System.DefaultWorkingDirectory)
  pythonVersion: 'PYTHON|3.12'

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(projectRoot)/app'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure Web App : '
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: $(azureServiceConnectionId)
    appType: 'webAppLinux'
    WebAppName: $(webAppName)
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    RuntimeStack: '$(pythonVersion)'
